name: TWoNEconomy
main: me.AxiusDevelopment.TWoNEconomy.Main
author: AxiusDevelopment
version: 2.3
commands:
    balance:
        description: Show your balance.
        aliases: [bal, money, cash]
    economy:
        description: Show your balance.
        aliases: [eco, econ, setmoney]
    pay:
        description: Show your balance.
        aliases: [givemoney]



